services:
  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    env_file:
        - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: realworld
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped
      
  realworld-nest-api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: realworld-nest-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always
volumes:
  postgres:
